version: "3"
services:
    server:
        image: localmapper
        command: tail -f /dev/null
        network_mode: host
        extra_hosts:
          - host.docker.internal:host-gateway
        volumes:
          - /home/phil/Desktop/GitHub/localmapper-server:/src
    mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        volumes:
          - mongodb-storage:/data/db
    web:
        image: php:8.1.7-apache
        ports:
          - 80:80
        volumes: 
          - /home/phil/Desktop/GitHub/localmapper-web:/var/www/html/
volumes: 
  mongodb-storage:
